# .github/workflows/lint.yml
name: Lint Codebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install flake8
      run: pip install flake8

    - name: Run flake8
      run: flake8 . --exclude=migrations,venv --max-line-length=100
